version: '2'
services:
  mongo:
    image: mongo:2.6
  elasticsearch:
    image: elasticsearch:1.7
  content:
    image: quay.io/deconst/content-service
    ports:
    - "9000:8080"
    environment:
      STORAGE:
      RACKSPACE_USERNAME:
      RACKSPACE_APIKEY:
      RACKSPACE_REGION:
      RACKSPACE_SERVICENET:
      ADMIN_APIKEY:
      CONTENT_CONTAINER:
      ASSET_CONTAINER:
      MONGODB_URL: mongodb://mongo:27017/content
      ELASTICSEARCH_HOST: http://elasticsearch:9200/
      CONTENT_LOG_LEVEL: DEBUG
      CONTENT_LOG_COLOR: "true"
    depends_on:
    - mongo
    - elasticsearch
  presenter:
    image: quay.io/deconst/presenter
    ports:
    - "80:8080"
    environment:
      CONTROL_REPO_PATH: /tmp/control-repo
      CONTROL_REPO_URL:
      CONTROL_REPO_BRANCH:
      CONTENT_SERVICE_URL: http://content:8080/
      PRESENTER_DIAGNOSTICS: "true"
      PRESENTED_URL_PROTO:
      PRESENTED_URL_DOMAIN:
      PRESENTER_LOG_LEVEL: DEBUG
      PRESENTER_DEVMODE:
      PRESENTER_LIVERELOAD:
      PRESENTER_LOG_JSON: "false"
      PRESENTER_LOG_COLOR: "true"
    depends_on:
    - content
  staging_content:
    image: quay.io/deconst/content-service
    ports:
    - "9001:8080"
    environment:
      STORAGE:
      RACKSPACE_USERNAME:
      RACKSPACE_APIKEY:
      RACKSPACE_REGION:
      RACKSPACE_SERVICENET:
      ADMIN_APIKEY:
      CONTENT_CONTAINER: "staging-${CONTENT_CONTAINER}"
      ASSET_CONTAINER: "staging-${ASSET_CONTAINER}"
      MONGODB_URL: mongodb://mongo:27017/content
      MONGODB_PREFIX: staging_
      ELASTICSEARCH_HOST: http://elasticsearch:9200/
      CONTENT_LOG_LEVEL: DEBUG
      CONTENT_LOG_COLOR: "true"
      PROXY_UPSTREAM: http://content:8080/
      STAGING_MODE: "true"
    depends_on:
    - mongo
    - content
  staging_presenter:
    image: quay.io/deconst/presenter
    ports:
    - "81:8080"
    environment:
      CONTROL_REPO_PATH: /tmp/control-repo
      CONTROL_REPO_URL:
      CONTROL_REPO_BRANCH:
      CONTENT_SERVICE_URL: http://staging_content:8080/
      PRESENTER_DIAGNOSTICS: "true"
      PRESENTED_URL_PROTO:
      PRESENTED_URL_DOMAIN:
      PRESENTER_LOG_LEVEL: DEBUG
      PRESENTER_DEVMODE:
      PRESENTER_LIVERELOAD:
      PRESENTER_LOG_JSON: "false"
      PRESENTER_LOG_COLOR: "true"
    depends_on:
    - staging_content
